'use strict';
try{
    let x = 10;
    // miFunction();
    }
    catch(error){
        console.log(error);
    }
    finally{
        console.log('Termina la revision de errores');
    }
console.log('Continuamos...')